In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datasets import load_dataset

In [6]:
print("PyCharm notebook is working")

PyCharm notebook is working

In [7]:
print(pd.__version__)

2.3.3

In [8]:
!python --version
!jupyter-notebook --version

Python 3.9.6
/Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
7.5.5

In [9]:
import sys
print(sys.executable)

/Users/hewiyoatl/udacity/aIProgrammingPython/venv/bin/python

In [10]:
!python -m pip install datasets pandas matplotlib seaborn pyarrow

Requirement already satisfied: datasets in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (4.5.0)
Requirement already satisfied: pandas in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: matplotlib in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (3.9.4)
Requirement already satisfied: seaborn in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (0.13.2)
Requirement already satisfied: pyarrow in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (21.0.0)
Requirement already satisfied: filelock in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from datasets) (3.19.1)
Requirement already satisfied: numpy>=1.17 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from datasets) (2.0.2)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from datasets) (0.4.0)
Requirement already satisfied: requests>=2.32.2 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from datasets) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from datasets) (0.70.18)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2025.10.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from datasets) (1.8.0)
Requirement already satisfied: packaging in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from datasets) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from pandas) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from matplotlib) (4.60.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: pillow>=8 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.3)
Requirement already satisfied: typer in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.23.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: zipp>=3.1.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.23.1)
Requirement already satisfied: six>=1.5 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: click>=8.0.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [11]:
sample_size = 100
print(sample_size)

100

In [13]:
from datasets import load_dataset
import pandas as pd
from itertools import islice

sample_size = 100

reviews_stream = load_dataset(
    "McAuley-Lab/Amazon-Reviews-2023",
    "raw_review_All_Beauty",
    split="full",
    streaming=True
)

reviews_df = pd.DataFrame(list(islice(reviews_stream, sample_size)))
reviews_df.head()

RuntimeError: Dataset scripts are no longer supported, but found Amazon-Reviews-2023.py

In [1]:
import datasets
print(datasets.__version__)

/Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

4.5.0

In [2]:
!python -m pip install "datasets<4.0.0" --upgrade --force-reinstall

Collecting datasets<4.0.0
  Downloading datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Collecting filelock (from datasets<4.0.0)
  Using cached filelock-3.19.1-py3-none-any.whl.metadata (2.1 kB)
Collecting numpy>=1.17 (from datasets<4.0.0)
  Using cached numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting pyarrow>=15.0.0 (from datasets<4.0.0)
  Using cached pyarrow-21.0.0-cp39-cp39-macosx_12_0_arm64.whl.metadata (3.3 kB)
Collecting dill<0.3.9,>=0.3.0 (from datasets<4.0.0)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Collecting pandas (from datasets<4.0.0)
  Using cached pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl.metadata (91 kB)
Collecting requests>=2.32.2 (from datasets<4.0.0)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting tqdm>=4.66.3 (from datasets<4.0.0)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting xxhash (from datasets<4.0.0)
  Using cached xxhash-3.6.0-cp39-cp39-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting multiprocess<0.70.17 (from datasets<4.0.0)
  Downloading multiprocess-0.70.16-py39-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2025.3.0,>=2023.1.0 (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Downloading fsspec-2025.3.0-py3-none-any.whl.metadata (11 kB)
Collecting huggingface-hub>=0.24.0 (from datasets<4.0.0)
  Using cached huggingface_hub-1.8.0-py3-none-any.whl.metadata (13 kB)
Collecting packaging (from datasets<4.0.0)
  Using cached packaging-26.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pyyaml>=5.1 (from datasets<4.0.0)
  Using cached pyyaml-6.0.3-cp39-cp39-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached aiohttp-3.13.5-cp39-cp39-macosx_11_0_arm64.whl.metadata (8.1 kB)
Collecting hf-xet<2.0.0,>=1.4.2 (from huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached hf_xet-1.4.3-cp37-abi3-macosx_11_0_arm64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting typer (from huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached typer-0.23.2-py3-none-any.whl.metadata (16 kB)
Collecting typing-extensions>=4.1.0 (from huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.32.2->datasets<4.0.0)
  Using cached charset_normalizer-3.4.7-cp39-cp39-macosx_10_9_universal2.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests>=2.32.2->datasets<4.0.0)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.32.2->datasets<4.0.0)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2017.4.17 (from requests>=2.32.2->datasets<4.0.0)
  Using cached certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting python-dateutil>=2.8.2 (from pandas->datasets<4.0.0)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas->datasets<4.0.0)
  Using cached pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas->datasets<4.0.0)
  Using cached tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting async-timeout<6.0,>=4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached async_timeout-5.0.1-py3-none-any.whl.metadata (5.1 kB)
Collecting attrs>=17.3.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached frozenlist-1.8.0-cp39-cp39-macosx_11_0_arm64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached multidict-6.7.1-cp39-cp39-macosx_11_0_arm64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached propcache-0.4.1-cp39-cp39-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached yarl-1.22.0-cp39-cp39-macosx_11_0_arm64.whl.metadata (75 kB)
Collecting anyio (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached anyio-4.12.1-py3-none-any.whl.metadata (4.3 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->datasets<4.0.0)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting click>=8.0.0 (from typer->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Collecting shellingham>=1.3.0 (from typer->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
Collecting exceptiongroup>=1.0.2 (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached exceptiongroup-1.3.1-py3-none-any.whl.metadata (6.7 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading datasets-3.6.0-py3-none-any.whl (491 kB)
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
Downloading fsspec-2025.3.0-py3-none-any.whl (193 kB)
Using cached huggingface_hub-1.8.0-py3-none-any.whl (625 kB)
Using cached filelock-3.19.1-py3-none-any.whl (15 kB)
Downloading multiprocess-0.70.16-py39-none-any.whl (133 kB)
Using cached numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
Using cached packaging-26.0-py3-none-any.whl (74 kB)
Using cached pyarrow-21.0.0-cp39-cp39-macosx_12_0_arm64.whl (31.2 MB)
Using cached pyyaml-6.0.3-cp39-cp39-macosx_11_0_arm64.whl (174 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Using cached pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
Using cached xxhash-3.6.0-cp39-cp39-macosx_11_0_arm64.whl (30 kB)
Using cached aiohttp-3.13.5-cp39-cp39-macosx_11_0_arm64.whl (499 kB)
Using cached certifi-2026.2.25-py3-none-any.whl (153 kB)
Using cached charset_normalizer-3.4.7-cp39-cp39-macosx_10_9_universal2.whl (299 kB)
Using cached hf_xet-1.4.3-cp37-abi3-macosx_11_0_arm64.whl (3.6 MB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached tzdata-2026.1-py2.py3-none-any.whl (348 kB)
Using cached urllib3-2.6.3-py3-none-any.whl (131 kB)
Using cached typer-0.23.2-py3-none-any.whl (56 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached click-8.1.8-py3-none-any.whl (98 kB)
Using cached frozenlist-1.8.0-cp39-cp39-macosx_11_0_arm64.whl (50 kB)
Using cached multidict-6.7.1-cp39-cp39-macosx_11_0_arm64.whl (44 kB)
Using cached propcache-0.4.1-cp39-cp39-macosx_11_0_arm64.whl (47 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached yarl-1.22.0-cp39-cp39-macosx_11_0_arm64.whl (94 kB)
Using cached anyio-4.12.1-py3-none-any.whl (113 kB)
Using cached exceptiongroup-1.3.1-py3-none-any.whl (16 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached pygments-2.20.0-py3-none-any.whl (1.2 MB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pytz, xxhash, urllib3, tzdata, typing-extensions, tqdm, six, shellingham, pyyaml, pygments, pyarrow, propcache, packaging, numpy, mdurl, idna, hf-xet, h11, fsspec, frozenlist, filelock, dill, click, charset_normalizer, certifi, attrs, async-timeout, annotated-doc, aiohappyeyeballs, requests, python-dateutil, multiprocess, multidict, markdown-it-py, httpcore, exceptiongroup, aiosignal, yarl, rich, pandas, anyio, typer, httpx, aiohttp, huggingface-hub, datasets
  Attempting uninstall: pytz
    Found existing installation: pytz 2026.1.post1
    Uninstalling pytz-2026.1.post1:
      Successfully uninstalled pytz-2026.1.post1
  Attempting uninstall: xxhash
    Found existing installation: xxhash 3.6.0
    Uninstalling xxhash-3.6.0:
      Successfully uninstalled xxhash-3.6.0
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.6.3
    Uninstalling urllib3-2.6.3:
      Successfully uninstalled urllib3-2.6.3
  Attempting uninstall: tzdata
    Found existing installation: tzdata 2026.1
    Uninstalling tzdata-2026.1:
      Successfully uninstalled tzdata-2026.1
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.15.0
    Uninstalling typing_extensions-4.15.0:
      Successfully uninstalled typing_extensions-4.15.0
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.3
    Uninstalling tqdm-4.67.3:
      Successfully uninstalled tqdm-4.67.3
  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
      Successfully uninstalled six-1.17.0
  Attempting uninstall: shellingham
    Found existing installation: shellingham 1.5.4
    Uninstalling shellingham-1.5.4:
      Successfully uninstalled shellingham-1.5.4
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
  Attempting uninstall: pygments
    Found existing installation: Pygments 2.20.0
    Uninstalling Pygments-2.20.0:
      Successfully uninstalled Pygments-2.20.0
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 21.0.0
    Uninstalling pyarrow-21.0.0:
      Successfully uninstalled pyarrow-21.0.0
  Attempting uninstall: propcache
    Found existing installation: propcache 0.4.1
    Uninstalling propcache-0.4.1:
      Successfully uninstalled propcache-0.4.1
  Attempting uninstall: packaging
    Found existing installation: packaging 26.0
    Uninstalling packaging-26.0:
      Successfully uninstalled packaging-26.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: mdurl
    Found existing installation: mdurl 0.1.2
    Uninstalling mdurl-0.1.2:
      Successfully uninstalled mdurl-0.1.2
  Attempting uninstall: idna
    Found existing installation: idna 3.11
    Uninstalling idna-3.11:
      Successfully uninstalled idna-3.11
  Attempting uninstall: hf-xet
    Found existing installation: hf-xet 1.4.3
    Uninstalling hf-xet-1.4.3:
      Successfully uninstalled hf-xet-1.4.3
  Attempting uninstall: h11
    Found existing installation: h11 0.16.0
    Uninstalling h11-0.16.0:
      Successfully uninstalled h11-0.16.0
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.10.0
    Uninstalling fsspec-2025.10.0:
      Successfully uninstalled fsspec-2025.10.0
  Attempting uninstall: frozenlist
    Found existing installation: frozenlist 1.8.0
    Uninstalling frozenlist-1.8.0:
      Successfully uninstalled frozenlist-1.8.0
  Attempting uninstall: filelock
    Found existing installation: filelock 3.19.1
    Uninstalling filelock-3.19.1:
      Successfully uninstalled filelock-3.19.1
  Attempting uninstall: dill
    Found existing installation: dill 0.4.0
    Uninstalling dill-0.4.0:
      Successfully uninstalled dill-0.4.0
  Attempting uninstall: click
    Found existing installation: click 8.1.8
    Uninstalling click-8.1.8:
      Successfully uninstalled click-8.1.8
  Attempting uninstall: charset_normalizer
    Found existing installation: charset-normalizer 3.4.7
    Uninstalling charset-normalizer-3.4.7:
      Successfully uninstalled charset-normalizer-3.4.7
  Attempting uninstall: certifi
    Found existing installation: certifi 2026.2.25
    Uninstalling certifi-2026.2.25:
      Successfully uninstalled certifi-2026.2.25
  Attempting uninstall: attrs
    Found existing installation: attrs 26.1.0
    Uninstalling attrs-26.1.0:
      Successfully uninstalled attrs-26.1.0
  Attempting uninstall: async-timeout
    Found existing installation: async-timeout 5.0.1
    Uninstalling async-timeout-5.0.1:
      Successfully uninstalled async-timeout-5.0.1
  Attempting uninstall: annotated-doc
    Found existing installation: annotated-doc 0.0.4
    Uninstalling annotated-doc-0.0.4:
      Successfully uninstalled annotated-doc-0.0.4
  Attempting uninstall: aiohappyeyeballs
    Found existing installation: aiohappyeyeballs 2.6.1
    Uninstalling aiohappyeyeballs-2.6.1:
      Successfully uninstalled aiohappyeyeballs-2.6.1
  Attempting uninstall: requests
    Found existing installation: requests 2.32.5
    Uninstalling requests-2.32.5:
      Successfully uninstalled requests-2.32.5
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
  Attempting uninstall: multiprocess
    Found existing installation: multiprocess 0.70.18
    Uninstalling multiprocess-0.70.18:
      Successfully uninstalled multiprocess-0.70.18
  Attempting uninstall: multidict
    Found existing installation: multidict 6.7.1
    Uninstalling multidict-6.7.1:
      Successfully uninstalled multidict-6.7.1
  Attempting uninstall: markdown-it-py
    Found existing installation: markdown-it-py 3.0.0
    Uninstalling markdown-it-py-3.0.0:
      Successfully uninstalled markdown-it-py-3.0.0
  Attempting uninstall: httpcore
    Found existing installation: httpcore 1.0.9
    Uninstalling httpcore-1.0.9:
      Successfully uninstalled httpcore-1.0.9
  Attempting uninstall: exceptiongroup
    Found existing installation: exceptiongroup 1.3.1
    Uninstalling exceptiongroup-1.3.1:
      Successfully uninstalled exceptiongroup-1.3.1
  Attempting uninstall: aiosignal
    Found existing installation: aiosignal 1.4.0
    Uninstalling aiosignal-1.4.0:
      Successfully uninstalled aiosignal-1.4.0
  Attempting uninstall: yarl
    Found existing installation: yarl 1.22.0
    Uninstalling yarl-1.22.0:
      Successfully uninstalled yarl-1.22.0
  Attempting uninstall: rich
    Found existing installation: rich 15.0.0
    Uninstalling rich-15.0.0:
      Successfully uninstalled rich-15.0.0
  Attempting uninstall: pandas
    Found existing installation: pandas 2.3.3
    Uninstalling pandas-2.3.3:
      Successfully uninstalled pandas-2.3.3
  Attempting uninstall: anyio
    Found existing installation: anyio 4.12.1
    Uninstalling anyio-4.12.1:
      Successfully uninstalled anyio-4.12.1
  Attempting uninstall: typer
    Found existing installation: typer 0.23.2
    Uninstalling typer-0.23.2:
      Successfully uninstalled typer-0.23.2
  Attempting uninstall: httpx
    Found existing installation: httpx 0.28.1
    Uninstalling httpx-0.28.1:
      Successfully uninstalled httpx-0.28.1
  Attempting uninstall: aiohttp
    Found existing installation: aiohttp 3.13.5
    Uninstalling aiohttp-3.13.5:
      Successfully uninstalled aiohttp-3.13.5
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.8.0
    Uninstalling huggingface_hub-1.8.0:
      Successfully uninstalled huggingface_hub-1.8.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.5.0
    Uninstalling datasets-4.5.0:
      Successfully uninstalled datasets-4.5.0
Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.13.5 aiosignal-1.4.0 annotated-doc-0.0.4 anyio-4.12.1 async-timeout-5.0.1 attrs-26.1.0 certifi-2026.2.25 charset_normalizer-3.4.7 click-8.1.8 datasets-3.6.0 dill-0.3.8 exceptiongroup-1.3.1 filelock-3.19.1 frozenlist-1.8.0 fsspec-2025.3.0 h11-0.16.0 hf-xet-1.4.3 httpcore-1.0.9 httpx-0.28.1 huggingface-hub-1.8.0 idna-3.11 markdown-it-py-3.0.0 mdurl-0.1.2 multidict-6.7.1 multiprocess-0.70.16 numpy-2.0.2 packaging-26.0 pandas-2.3.3 propcache-0.4.1 pyarrow-21.0.0 pygments-2.20.0 python-dateutil-2.9.0.post0 pytz-2026.1.post1 pyyaml-6.0.3 requests-2.32.5 rich-15.0.0 shellingham-1.5.4 six-1.17.0 tqdm-4.67.3 typer-0.23.2 typing-extensions-4.15.0 tzdata-2026.1 urllib3-2.6.3 xxhash-3.6.0 yarl-1.22.0

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [1]:
!python -m pip install "datasets<4.0.0" --upgrade --force-reinstall

Collecting datasets<4.0.0
  Using cached datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Collecting filelock (from datasets<4.0.0)
  Using cached filelock-3.19.1-py3-none-any.whl.metadata (2.1 kB)
Collecting numpy>=1.17 (from datasets<4.0.0)
  Using cached numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting pyarrow>=15.0.0 (from datasets<4.0.0)
  Using cached pyarrow-21.0.0-cp39-cp39-macosx_12_0_arm64.whl.metadata (3.3 kB)
Collecting dill<0.3.9,>=0.3.0 (from datasets<4.0.0)
  Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Collecting pandas (from datasets<4.0.0)
  Using cached pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl.metadata (91 kB)
Collecting requests>=2.32.2 (from datasets<4.0.0)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting tqdm>=4.66.3 (from datasets<4.0.0)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting xxhash (from datasets<4.0.0)
  Using cached xxhash-3.6.0-cp39-cp39-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting multiprocess<0.70.17 (from datasets<4.0.0)
  Using cached multiprocess-0.70.16-py39-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2025.3.0,>=2023.1.0 (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached fsspec-2025.3.0-py3-none-any.whl.metadata (11 kB)
Collecting huggingface-hub>=0.24.0 (from datasets<4.0.0)
  Using cached huggingface_hub-1.8.0-py3-none-any.whl.metadata (13 kB)
Collecting packaging (from datasets<4.0.0)
  Using cached packaging-26.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pyyaml>=5.1 (from datasets<4.0.0)
  Using cached pyyaml-6.0.3-cp39-cp39-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached aiohttp-3.13.5-cp39-cp39-macosx_11_0_arm64.whl.metadata (8.1 kB)
Collecting hf-xet<2.0.0,>=1.4.2 (from huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached hf_xet-1.4.3-cp37-abi3-macosx_11_0_arm64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting typer (from huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached typer-0.23.2-py3-none-any.whl.metadata (16 kB)
Collecting typing-extensions>=4.1.0 (from huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.32.2->datasets<4.0.0)
  Using cached charset_normalizer-3.4.7-cp39-cp39-macosx_10_9_universal2.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests>=2.32.2->datasets<4.0.0)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.32.2->datasets<4.0.0)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2017.4.17 (from requests>=2.32.2->datasets<4.0.0)
  Using cached certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting python-dateutil>=2.8.2 (from pandas->datasets<4.0.0)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas->datasets<4.0.0)
  Using cached pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas->datasets<4.0.0)
  Using cached tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting async-timeout<6.0,>=4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached async_timeout-5.0.1-py3-none-any.whl.metadata (5.1 kB)
Collecting attrs>=17.3.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached frozenlist-1.8.0-cp39-cp39-macosx_11_0_arm64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached multidict-6.7.1-cp39-cp39-macosx_11_0_arm64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached propcache-0.4.1-cp39-cp39-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0)
  Using cached yarl-1.22.0-cp39-cp39-macosx_11_0_arm64.whl.metadata (75 kB)
Collecting anyio (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached anyio-4.12.1-py3-none-any.whl.metadata (4.3 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->datasets<4.0.0)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting click>=8.0.0 (from typer->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Collecting shellingham>=1.3.0 (from typer->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
Collecting exceptiongroup>=1.0.2 (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached exceptiongroup-1.3.1-py3-none-any.whl.metadata (6.7 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets<4.0.0)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached datasets-3.6.0-py3-none-any.whl (491 kB)
Using cached dill-0.3.8-py3-none-any.whl (116 kB)
Using cached fsspec-2025.3.0-py3-none-any.whl (193 kB)
Using cached huggingface_hub-1.8.0-py3-none-any.whl (625 kB)
Using cached filelock-3.19.1-py3-none-any.whl (15 kB)
Using cached multiprocess-0.70.16-py39-none-any.whl (133 kB)
Using cached numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
Using cached packaging-26.0-py3-none-any.whl (74 kB)
Using cached pyarrow-21.0.0-cp39-cp39-macosx_12_0_arm64.whl (31.2 MB)
Using cached pyyaml-6.0.3-cp39-cp39-macosx_11_0_arm64.whl (174 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Using cached pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
Using cached xxhash-3.6.0-cp39-cp39-macosx_11_0_arm64.whl (30 kB)
Using cached aiohttp-3.13.5-cp39-cp39-macosx_11_0_arm64.whl (499 kB)
Using cached certifi-2026.2.25-py3-none-any.whl (153 kB)
Using cached charset_normalizer-3.4.7-cp39-cp39-macosx_10_9_universal2.whl (299 kB)
Using cached hf_xet-1.4.3-cp37-abi3-macosx_11_0_arm64.whl (3.6 MB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached tzdata-2026.1-py2.py3-none-any.whl (348 kB)
Using cached urllib3-2.6.3-py3-none-any.whl (131 kB)
Using cached typer-0.23.2-py3-none-any.whl (56 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached click-8.1.8-py3-none-any.whl (98 kB)
Using cached frozenlist-1.8.0-cp39-cp39-macosx_11_0_arm64.whl (50 kB)
Using cached multidict-6.7.1-cp39-cp39-macosx_11_0_arm64.whl (44 kB)
Using cached propcache-0.4.1-cp39-cp39-macosx_11_0_arm64.whl (47 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached yarl-1.22.0-cp39-cp39-macosx_11_0_arm64.whl (94 kB)
Using cached anyio-4.12.1-py3-none-any.whl (113 kB)
Using cached exceptiongroup-1.3.1-py3-none-any.whl (16 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached pygments-2.20.0-py3-none-any.whl (1.2 MB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pytz, xxhash, urllib3, tzdata, typing-extensions, tqdm, six, shellingham, pyyaml, pygments, pyarrow, propcache, packaging, numpy, mdurl, idna, hf-xet, h11, fsspec, frozenlist, filelock, dill, click, charset_normalizer, certifi, attrs, async-timeout, annotated-doc, aiohappyeyeballs, requests, python-dateutil, multiprocess, multidict, markdown-it-py, httpcore, exceptiongroup, aiosignal, yarl, rich, pandas, anyio, typer, httpx, aiohttp, huggingface-hub, datasets
  Attempting uninstall: pytz
    Found existing installation: pytz 2026.1.post1
    Uninstalling pytz-2026.1.post1:
      Successfully uninstalled pytz-2026.1.post1
  Attempting uninstall: xxhash
    Found existing installation: xxhash 3.6.0
    Uninstalling xxhash-3.6.0:
      Successfully uninstalled xxhash-3.6.0
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.6.3
    Uninstalling urllib3-2.6.3:
      Successfully uninstalled urllib3-2.6.3
  Attempting uninstall: tzdata
    Found existing installation: tzdata 2026.1
    Uninstalling tzdata-2026.1:
      Successfully uninstalled tzdata-2026.1
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.15.0
    Uninstalling typing_extensions-4.15.0:
      Successfully uninstalled typing_extensions-4.15.0
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.3
    Uninstalling tqdm-4.67.3:
      Successfully uninstalled tqdm-4.67.3
  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
      Successfully uninstalled six-1.17.0
  Attempting uninstall: shellingham
    Found existing installation: shellingham 1.5.4
    Uninstalling shellingham-1.5.4:
      Successfully uninstalled shellingham-1.5.4
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
  Attempting uninstall: pygments
    Found existing installation: Pygments 2.20.0
    Uninstalling Pygments-2.20.0:
      Successfully uninstalled Pygments-2.20.0
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 21.0.0
    Uninstalling pyarrow-21.0.0:
      Successfully uninstalled pyarrow-21.0.0
  Attempting uninstall: propcache
    Found existing installation: propcache 0.4.1
    Uninstalling propcache-0.4.1:
      Successfully uninstalled propcache-0.4.1
  Attempting uninstall: packaging
    Found existing installation: packaging 26.0
    Uninstalling packaging-26.0:
      Successfully uninstalled packaging-26.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: mdurl
    Found existing installation: mdurl 0.1.2
    Uninstalling mdurl-0.1.2:
      Successfully uninstalled mdurl-0.1.2
  Attempting uninstall: idna
    Found existing installation: idna 3.11
    Uninstalling idna-3.11:
      Successfully uninstalled idna-3.11
  Attempting uninstall: hf-xet
    Found existing installation: hf-xet 1.4.3
    Uninstalling hf-xet-1.4.3:
      Successfully uninstalled hf-xet-1.4.3
  Attempting uninstall: h11
    Found existing installation: h11 0.16.0
    Uninstalling h11-0.16.0:
      Successfully uninstalled h11-0.16.0
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
  Attempting uninstall: frozenlist
    Found existing installation: frozenlist 1.8.0
    Uninstalling frozenlist-1.8.0:
      Successfully uninstalled frozenlist-1.8.0
  Attempting uninstall: filelock
    Found existing installation: filelock 3.19.1
    Uninstalling filelock-3.19.1:
      Successfully uninstalled filelock-3.19.1
  Attempting uninstall: dill
    Found existing installation: dill 0.3.8
    Uninstalling dill-0.3.8:
      Successfully uninstalled dill-0.3.8
  Attempting uninstall: click
    Found existing installation: click 8.1.8
    Uninstalling click-8.1.8:
      Successfully uninstalled click-8.1.8
  Attempting uninstall: charset_normalizer
    Found existing installation: charset-normalizer 3.4.7
    Uninstalling charset-normalizer-3.4.7:
      Successfully uninstalled charset-normalizer-3.4.7
  Attempting uninstall: certifi
    Found existing installation: certifi 2026.2.25
    Uninstalling certifi-2026.2.25:
      Successfully uninstalled certifi-2026.2.25
  Attempting uninstall: attrs
    Found existing installation: attrs 26.1.0
    Uninstalling attrs-26.1.0:
      Successfully uninstalled attrs-26.1.0
  Attempting uninstall: async-timeout
    Found existing installation: async-timeout 5.0.1
    Uninstalling async-timeout-5.0.1:
      Successfully uninstalled async-timeout-5.0.1
  Attempting uninstall: annotated-doc
    Found existing installation: annotated-doc 0.0.4
    Uninstalling annotated-doc-0.0.4:
      Successfully uninstalled annotated-doc-0.0.4
  Attempting uninstall: aiohappyeyeballs
    Found existing installation: aiohappyeyeballs 2.6.1
    Uninstalling aiohappyeyeballs-2.6.1:
      Successfully uninstalled aiohappyeyeballs-2.6.1
  Attempting uninstall: requests
    Found existing installation: requests 2.32.5
    Uninstalling requests-2.32.5:
      Successfully uninstalled requests-2.32.5
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
  Attempting uninstall: multiprocess
    Found existing installation: multiprocess 0.70.16
    Uninstalling multiprocess-0.70.16:
      Successfully uninstalled multiprocess-0.70.16
  Attempting uninstall: multidict
    Found existing installation: multidict 6.7.1
    Uninstalling multidict-6.7.1:
      Successfully uninstalled multidict-6.7.1
  Attempting uninstall: markdown-it-py
    Found existing installation: markdown-it-py 3.0.0
    Uninstalling markdown-it-py-3.0.0:
      Successfully uninstalled markdown-it-py-3.0.0
  Attempting uninstall: httpcore
    Found existing installation: httpcore 1.0.9
    Uninstalling httpcore-1.0.9:
      Successfully uninstalled httpcore-1.0.9
  Attempting uninstall: exceptiongroup
    Found existing installation: exceptiongroup 1.3.1
    Uninstalling exceptiongroup-1.3.1:
      Successfully uninstalled exceptiongroup-1.3.1
  Attempting uninstall: aiosignal
    Found existing installation: aiosignal 1.4.0
    Uninstalling aiosignal-1.4.0:
      Successfully uninstalled aiosignal-1.4.0
  Attempting uninstall: yarl
    Found existing installation: yarl 1.22.0
    Uninstalling yarl-1.22.0:
      Successfully uninstalled yarl-1.22.0
  Attempting uninstall: rich
    Found existing installation: rich 15.0.0
    Uninstalling rich-15.0.0:
      Successfully uninstalled rich-15.0.0
  Attempting uninstall: pandas
    Found existing installation: pandas 2.3.3
    Uninstalling pandas-2.3.3:
      Successfully uninstalled pandas-2.3.3
  Attempting uninstall: anyio
    Found existing installation: anyio 4.12.1
    Uninstalling anyio-4.12.1:
      Successfully uninstalled anyio-4.12.1
  Attempting uninstall: typer
    Found existing installation: typer 0.23.2
    Uninstalling typer-0.23.2:
      Successfully uninstalled typer-0.23.2
  Attempting uninstall: httpx
    Found existing installation: httpx 0.28.1
    Uninstalling httpx-0.28.1:
      Successfully uninstalled httpx-0.28.1
  Attempting uninstall: aiohttp
    Found existing installation: aiohttp 3.13.5
    Uninstalling aiohttp-3.13.5:
      Successfully uninstalled aiohttp-3.13.5
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.8.0
    Uninstalling huggingface_hub-1.8.0:
      Successfully uninstalled huggingface_hub-1.8.0
  Attempting uninstall: datasets
    Found existing installation: datasets 3.6.0
    Uninstalling datasets-3.6.0:
      Successfully uninstalled datasets-3.6.0
Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.13.5 aiosignal-1.4.0 annotated-doc-0.0.4 anyio-4.12.1 async-timeout-5.0.1 attrs-26.1.0 certifi-2026.2.25 charset_normalizer-3.4.7 click-8.1.8 datasets-3.6.0 dill-0.3.8 exceptiongroup-1.3.1 filelock-3.19.1 frozenlist-1.8.0 fsspec-2025.3.0 h11-0.16.0 hf-xet-1.4.3 httpcore-1.0.9 httpx-0.28.1 huggingface-hub-1.8.0 idna-3.11 markdown-it-py-3.0.0 mdurl-0.1.2 multidict-6.7.1 multiprocess-0.70.16 numpy-2.0.2 packaging-26.0 pandas-2.3.3 propcache-0.4.1 pyarrow-21.0.0 pygments-2.20.0 python-dateutil-2.9.0.post0 pytz-2026.1.post1 pyyaml-6.0.3 requests-2.32.5 rich-15.0.0 shellingham-1.5.4 six-1.17.0 tqdm-4.67.3 typer-0.23.2 typing-extensions-4.15.0 tzdata-2026.1 urllib3-2.6.3 xxhash-3.6.0 yarl-1.22.0

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [1]:
import datasets
print(datasets.__version__)

/Users/hewiyoatl/udacity/aIProgrammingPython/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

3.6.0

In [7]:
from datasets import load_dataset
import pandas as pd

sample_size = 100

reviews_ds = load_dataset(
    "McAuley-Lab/Amazon-Reviews-2023",
    "raw_review_All_Beauty",
    split=f"full[:{sample_size}]",
    trust_remote_code=True
)

reviews_df = pd.DataFrame(reviews_ds)
reviews_df.head()

raw/review_categories/All_Beauty.jsonl:   0%|          | 0.00/327M [00:00<?, ?B/s]

Generating full split: 0 examples [00:00, ? examples/s]

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Such a lovely scent but not overpowering.,This spray is really nice. It smells really go...,[],B00YQ6X8EO,B00YQ6X8EO,AGKHLEW2SOWHNMFQIJGBECAF7INQ,1588687728923,0,True
1,4.0,Works great but smells a little weird.,"This product does what I need it to do, I just...",[],B081TJ8YS3,B081TJ8YS3,AGKHLEW2SOWHNMFQIJGBECAF7INQ,1588615855070,1,True
2,5.0,Yes!,"Smells good, feels great!",[],B07PNNCSP9,B097R46CSY,AE74DYR3QUGVPZJ3P7RFWBGIX7XQ,1589665266052,2,True
3,1.0,Synthetic feeling,Felt synthetic,[],B09JS339BZ,B09JS339BZ,AFQLNQNQYFWQZPJQZS6V3NZU4QBQ,1643393630220,0,True
4,5.0,A+,Love it,[],B08BZ63GMJ,B08BZ63GMJ,AFQLNQNQYFWQZPJQZS6V3NZU4QBQ,1609322563534,0,True

In [8]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rating             100 non-null    float64
 1   title              100 non-null    object
 2   text               100 non-null    object
 3   images             100 non-null    object
 4   asin               100 non-null    object
 5   parent_asin        100 non-null    object
 6   user_id            100 non-null    object
 7   timestamp          100 non-null    int64
 8   helpful_vote       100 non-null    int64
 9   verified_purchase  100 non-null    bool
dtypes: bool(1), float64(1), int64(2), object(6)
memory usage: 7.3+ KB

In [9]:
reviews_df.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Such a lovely scent but not overpowering.,This spray is really nice. It smells really go...,[],B00YQ6X8EO,B00YQ6X8EO,AGKHLEW2SOWHNMFQIJGBECAF7INQ,1588687728923,0,True
1,4.0,Works great but smells a little weird.,"This product does what I need it to do, I just...",[],B081TJ8YS3,B081TJ8YS3,AGKHLEW2SOWHNMFQIJGBECAF7INQ,1588615855070,1,True
2,5.0,Yes!,"Smells good, feels great!",[],B07PNNCSP9,B097R46CSY,AE74DYR3QUGVPZJ3P7RFWBGIX7XQ,1589665266052,2,True
3,1.0,Synthetic feeling,Felt synthetic,[],B09JS339BZ,B09JS339BZ,AFQLNQNQYFWQZPJQZS6V3NZU4QBQ,1643393630220,0,True
4,5.0,A+,Love it,[],B08BZ63GMJ,B08BZ63GMJ,AFQLNQNQYFWQZPJQZS6V3NZU4QBQ,1609322563534,0,True

In [10]:
from datasets import load_dataset
import pandas as pd

sample_size = 100

metadata_ds = load_dataset(
    "McAuley-Lab/Amazon-Reviews-2023",
    "raw_meta_All_Beauty",
    split=f"full[:{sample_size}]",
    trust_remote_code=True
)

metadata_df = pd.DataFrame(metadata_ds)
metadata_df.head()

raw/meta_categories/meta_All_Beauty.json(…):   0%|          | 0.00/213M [00:00<?, ?B/s]

Generating full split:   0%|          | 0/112590 [00:00<?, ? examples/s]

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Beauty,"Howard LC0008 Leather Conditioner, 8-Ounce (4-...",4.8,10,[],[],None,"{'hi_res': [None, 'https://m.media-amazon.com/...","{'title': [], 'url': [], 'user_id': []}",Howard Products,[],"{""Package Dimensions"": ""7.1 x 5.5 x 3 inches; ...",B01CUPMQZE,None,None,None
1,All Beauty,Yes to Tomatoes Detoxifying Charcoal Cleanser ...,4.5,3,[],[],None,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Yes To,[],"{""Item Form"": ""Powder"", ""Skin Type"": ""Acne Pro...",B076WQZGPM,None,None,None
2,All Beauty,Eye Patch Black Adult with Tie Band (6 Per Pack),4.4,26,[],[],None,"{'hi_res': [None, None], 'large': ['https://m....","{'title': [], 'url': [], 'user_id': []}",Levine Health Products,[],"{""Manufacturer"": ""Levine Health Products""}",B000B658RI,None,None,None
3,All Beauty,"Tattoo Eyebrow Stickers, Waterproof Eyebrow, 4...",3.1,102,[],[],None,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Cherioll,[],"{""Brand"": ""Cherioll"", ""Item Form"": ""Powder"", ""...",B088FKY3VD,None,None,None
4,All Beauty,Precision Plunger Bars for Cartridge Grips – 9...,4.3,7,"[Material: 304 Stainless Steel; Brass tip, Len...",[The Precision Plunger Bars are designed to wo...,None,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Precision,[],"{""UPC"": ""644287689178""}",B07NGFDN6G,None,None,None

In [11]:
metadata_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   main_category    100 non-null    object
 1   title            100 non-null    object
 2   average_rating   100 non-null    float64
 3   rating_number    100 non-null    int64
 4   features         100 non-null    object
 5   description      100 non-null    object
 6   price            100 non-null    object
 7   images           100 non-null    object
 8   videos           100 non-null    object
 9   store            94 non-null     object
 10  categories       100 non-null    object
 11  details          100 non-null    object
 12  parent_asin      100 non-null    object
 13  bought_together  0 non-null      object
 14  subtitle         0 non-null      object
 15  author           0 non-null      object
dtypes: float64(1), int64(1), object(14)
memory usage: 12.6+ KB

In [12]:
metadata_df.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Beauty,"Howard LC0008 Leather Conditioner, 8-Ounce (4-...",4.8,10,[],[],None,"{'hi_res': [None, 'https://m.media-amazon.com/...","{'title': [], 'url': [], 'user_id': []}",Howard Products,[],"{""Package Dimensions"": ""7.1 x 5.5 x 3 inches; ...",B01CUPMQZE,None,None,None
1,All Beauty,Yes to Tomatoes Detoxifying Charcoal Cleanser ...,4.5,3,[],[],None,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Yes To,[],"{""Item Form"": ""Powder"", ""Skin Type"": ""Acne Pro...",B076WQZGPM,None,None,None
2,All Beauty,Eye Patch Black Adult with Tie Band (6 Per Pack),4.4,26,[],[],None,"{'hi_res': [None, None], 'large': ['https://m....","{'title': [], 'url': [], 'user_id': []}",Levine Health Products,[],"{""Manufacturer"": ""Levine Health Products""}",B000B658RI,None,None,None
3,All Beauty,"Tattoo Eyebrow Stickers, Waterproof Eyebrow, 4...",3.1,102,[],[],None,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Cherioll,[],"{""Brand"": ""Cherioll"", ""Item Form"": ""Powder"", ""...",B088FKY3VD,None,None,None
4,All Beauty,Precision Plunger Bars for Cartridge Grips – 9...,4.3,7,"[Material: 304 Stainless Steel; Brass tip, Len...",[The Precision Plunger Bars are designed to wo...,None,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Precision,[],"{""UPC"": ""644287689178""}",B07NGFDN6G,None,None,None

In [17]:
import pandas as pd

def get_product_info(parent_asin, metadata_df):
    try:
        product_row = metadata_df.loc[metadata_df["parent_asin"] == parent_asin].iloc[0]
        title = product_row["title"]

        price = pd.to_numeric(product_row["price"], errors="coerce")

        if pd.isna(price):
            price = None

        return title, price

    except (IndexError, KeyError):
        return None, None

In [18]:
test_asin = metadata_df["parent_asin"].iloc[0]
print(get_product_info(test_asin, metadata_df))

('Howard LC0008 Leather Conditioner, 8-Ounce (4-Pack)', None)